import {
  ServiceCategory,
  ServiceItem,
  PriceRow,
  GalleryItem,
  OpeningHour,
  BusinessSettings,
  BrandSettings,
  DesignSectionSetting,
  ContentSection,
  SeoSetting,
} from "./types";

export const DEFAULT_CATEGORIES: ServiceCategory[] = [
  {
    id: 1,
    name: "Wimpern",
    slug: "wimpern",
    description: "Präzise Wimpernverlängerung von natürlicher 1:1 Technik bis Mega Volumen sowie pflegendes Lash Lifting.",
    display_order: 1,
    is_active: true,
  },
  {
    id: 2,
    name: "Gesichtsreinigung & Pflege",
    slug: "gesichtsreinigung-pflege",
    description: "Hautverfeinernde apparative Behandlungen für Tiefenregeneration, Anti-Aging und den unverwechselbaren Hollywood Glow.",
    display_order: 2,
    is_active: true,
  },
  {
    id: 3,
    name: "Permanent Make-up",
    slug: "permanent-make-up",
    description: "Meisterhafte Pigmentierung für perfekt definierte Powder Brows, Ombré Brows und sinnliche Lippen im Aquarell-Look.",
    display_order: 3,
    is_active: true,
  },
  {
    id: 4,
    name: "Schulungen",
    slug: "schulungen",
    description: "Zertifizierte Einzelschulungen für angehende Lash- und PMU-Artists nach modernsten europäischen Techniken.",
    display_order: 4,
    is_active: true,
  },
];

export const DEFAULT_SERVICES: ServiceItem[] = [
  // Wimpern
  {
    id: 1,
    category_id: 1,
    category_name: "Wimpern",
    title: "Klassische Wimpernverlängerung",
    slug: "wimpern-klassisch",
    short_description: "Elegante 1:1 Einzeltechnik für einen dezenten, natürlich dichten und typgerechten Augenaufschlag.",
    full_description: "Bei der klassischen 1:1 Methode wird auf jede gesunde Naturwimper eine einzelne synthetische Seidenwimper appliziert. Ideal für alle, die einen gepflegten Mascara-Effekt ohne Verklumpen wünschen.",
    featured_image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 90,
    price_display: "ab 60 €",
    price: 60,
    is_featured: true,
    display_order: 1,
    is_active: true,
    seo_title: "Klassische Wimpernverlängerung Peine | Aura Glow by Mürvet",
    seo_description: "Präzise 1:1 Wimpernverlängerung für einen natürlichen, eleganten Mascara-Look.",
  },
  {
    id: 2,
    category_id: 1,
    category_name: "Wimpern",
    title: "Volumen Soft / Medium",
    slug: "wimpern-volumen-soft-medium",
    short_description: "Feinste handgefertigte Fächer (2D–3D) für samtige Fülle und ausdrucksstarke Blicke.",
    full_description: "Leichte, mikrofeine Wimpernfächer sorgen für einen samtigen, volleren Look, der die Augen öffnet und dennoch federleicht zu tragen ist.",
    featured_image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 105,
    price_display: "ab 80 €",
    price: 80,
    is_featured: true,
    display_order: 2,
    is_active: true,
    seo_title: "Volumenwimpern Soft & Medium | Aura Glow by Mürvet",
    seo_description: "Samtiges Wimpernvolumen mit federleichten 2D-3D Fächern für strahlende Augenblicke.",
  },
  {
    id: 3,
    category_id: 1,
    category_name: "Wimpern",
    title: "Mega & Russian Volumen",
    slug: "wimpern-mega-russian-volumen",
    short_description: "Dichte, tiefschwarze Fülle für glamouröse Augenblicke mit maximaler Haltbarkeit.",
    full_description: "Hochpräzise Fächertechnik mit ultrafeinen Fasern (4D–6D). Schafft einen dichten Wimpernkranz mit atemberaubender Tiefenwirkung.",
    featured_image: "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 120,
    price_display: "ab 95 €",
    price: 95,
    is_featured: false,
    display_order: 3,
    is_active: true,
  },
  {
    id: 4,
    category_id: 1,
    category_name: "Wimpern",
    title: "Wimpernlifting & Keratinpflege",
    slug: "wimpernlifting",
    short_description: "Sanfter Schwung für die eigenen Naturwimpern inklusive nährender Keratinlaminierung.",
    full_description: "Lash Lifting glättet, hebt und streckt die eigenen Naturwimpern schonend vom Ansatz an nach oben. Hält 6 bis 8 Wochen.",
    featured_image: "/images/treatments/lash-lift-result.jpg",
    duration_minutes: 60,
    price_display: "ab 50 €",
    price: 50,
    is_featured: true,
    display_order: 4,
    is_active: true,
  },

  // Gesichtsreinigung & Pflege
  {
    id: 5,
    category_id: 2,
    category_name: "Gesichtsreinigung & Pflege",
    title: "Hollywood Glow Treatment",
    slug: "hollywood-glow",
    short_description: "Das Signature Facial für sofortigen Feuchtigkeitskick, verfeinerte Poren und strahlenden Teint.",
    full_description: "Tiefenreinigende Wirkstoffinfusion kombiniert mit hochkonzentrierten Seren. Hinterlässt die Haut seidig glatt, prall und makellos strahlend.",
    featured_image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 60,
    price_display: "95 €",
    price: 95,
    is_featured: true,
    display_order: 5,
    is_active: true,
    seo_title: "Hollywood Glow Facial Peine | Aura Glow by Mürvet",
    seo_description: "Das exklusive Signature Facial für porentiefe Reinheit und unwiderstehlichen Glow.",
  },
  {
    id: 6,
    category_id: 2,
    category_name: "Gesichtsreinigung & Pflege",
    title: "Microneedling Kollagen-Therapie",
    slug: "microneedling",
    short_description: "Gezielte Zellerneuerung zur Narbenverfeinerung, Festigung und Faltenminderung.",
    full_description: "Mikrofeine Nadelimpulse stimulieren die körpereigene Kollagen- und Elastinbildung. Wirkstoffe penetrieren tief in die Dermis für langanhaltende Glättung.",
    featured_image: "/images/treatments/microneedling-facial.jpg",
    duration_minutes: 75,
    price_display: "90 €",
    price: 90,
    is_featured: true,
    display_order: 6,
    is_active: true,
  },
  {
    id: 7,
    category_id: 2,
    category_name: "Gesichtsreinigung & Pflege",
    title: "Gesichtsreinigung inkl. Anti-Aging",
    slug: "gesichtsreinigung-anti-aging",
    short_description: "Klassische Tiefenreinigung mit Dampf, Peeling, Ausreinigung und regenerierender Anti-Aging Maske.",
    full_description: "Entfernt Talgüberschüsse und Verhornungen, klärt das Hautbild und versorgt anspruchsvolle Haut mit Antioxidantien und Feuchtigkeit.",
    featured_image: "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 60,
    price_display: "80 €",
    price: 80,
    is_featured: false,
    display_order: 7,
    is_active: true,
  },
  {
    id: 8,
    category_id: 2,
    category_name: "Gesichtsreinigung & Pflege",
    title: "Hollywood Peel (Carbon Laser)",
    slug: "hollywood-peel",
    short_description: "Modernste Schälung für verfeinerte Poren, ebenmäßigen Ton und seidig glattes Hautgefühl.",
    full_description: "90-minütige Premium-Behandlung für alle, die eine sofortige Verbesserung der Hautstruktur ohne lange Ausfallzeit suchen.",
    featured_image: "https://images.unsplash.com/photo-1512290900672-1f55b9a5c88b?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 90,
    price_display: "120 €",
    price: 120,
    is_featured: false,
    display_order: 8,
    is_active: true,
  },

  // Permanent Make-up
  {
    id: 9,
    category_id: 3,
    category_name: "Permanent Make-up",
    title: "Powder Brows (Puder-Augenbrauen)",
    slug: "powder-brows",
    short_description: "Sanfte Schattierungstechnik für natürliche Dichte und perfekt definierte Augenbrauen.",
    full_description: "Durch feine Mikropunktierung entsteht ein natürlicher, pudriger Farbverlauf, der die Brauen optisch auffüllt und definiert.",
    featured_image: "https://images.unsplash.com/photo-1597225244660-1cd128c64284?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 150,
    price_display: "350 €",
    price: 350,
    is_featured: true,
    display_order: 9,
    is_active: true,
    seo_title: "Powder Brows Peine | Aura Glow by Mürvet",
    seo_description: "Natürliche Puder-Augenbrauen mit meisterhafter Schattierung und langer Haltbarkeit.",
  },
  {
    id: 10,
    category_id: 3,
    category_name: "Permanent Make-up",
    title: "Ombré Brows",
    slug: "ombre-brows",
    short_description: "Fließender Farbverlauf von transparent-hell am Brauenkopf zu intensiv-definiert am Schwanz.",
    full_description: "Die Königsklasse des Permanent Make-ups: sorgt für einen eleganten 3D-Look mit meisterhafter Schattierung.",
    featured_image: "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 150,
    price_display: "350 €",
    price: 350,
    is_featured: false,
    display_order: 10,
    is_active: true,
  },
  {
    id: 11,
    category_id: 3,
    category_name: "Permanent Make-up",
    title: "Lippenpigmentierung (Aquarell / Soft Lips)",
    slug: "lippen-pigmentierung",
    short_description: "Sanfte Lippenkonturierung und Vollschattierung für frische Farbe und optisches Volumen.",
    full_description: "Verleiht blassen oder unregelmäßigen Lippenkonturen eine frische, lebendige Farbe und optische Symmetrie.",
    featured_image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 180,
    price_display: "ab 300 €",
    price: 300,
    is_featured: true,
    display_order: 11,
    is_active: true,
  },

  // Schulungen
  {
    id: 12,
    category_id: 4,
    category_name: "Schulungen",
    title: "Masterclass Wimpernverlängerung",
    slug: "schulung-wimpern",
    short_description: "Umfassende Intensivausbildung in 1:1- und Volumentechnik mit Theorie, Praxis und Zertifikat.",
    full_description: "Lerne die Kunst der professionellen Wimpernapplikation von Grund auf inklusive Hygiene, Anatomie, Fächertechnik und Kundenberatung.",
    featured_image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 480,
    price_display: "900 €",
    price: 900,
    is_featured: true,
    display_order: 12,
    is_active: true,
  },
  {
    id: 13,
    category_id: 4,
    category_name: "Schulungen",
    title: "Masterclass Permanent Make-up",
    slug: "schulung-pmu",
    short_description: "Praxisorientierte PMU-Ausbildung für Powder Brows und Lippenpigmentierung.",
    full_description: "Erlange meisterhafte Präzision an Pigmentiergeräten, Farblehre, Nadelmodulen und Hauttypen.",
    featured_image: "https://images.unsplash.com/photo-1597225244660-1cd128c64284?auto=format&fit=crop&w=1000&q=85",
    duration_minutes: 960,
    price_display: "1.500 €",
    price: 1500,
    is_featured: true,
    display_order: 13,
    is_active: true,
  },
];

export const DEFAULT_PRICING: PriceRow[] = [
  // WIMPERN — Klassisch
  { id: 1, category_id: 1, subcategory_name: "Klassisch", treatment_name: "Klassische Wimpernverlängerung", variant_name: "Neuset", duration: "90 Min.", price: 60, price_display: "60 €", display_order: 1, is_active: true },
  { id: 2, category_id: 1, subcategory_name: "Klassisch", treatment_name: "Klassische Wimpernverlängerung", variant_name: "Auffüllen 3 Wochen", duration: "60 Min.", price: 40, price_display: "40 €", display_order: 2, is_active: true },
  { id: 3, category_id: 1, subcategory_name: "Klassisch", treatment_name: "Klassische Wimpernverlängerung", variant_name: "Auffüllen 4 Wochen", duration: "75 Min.", price: 50, price_display: "50 €", display_order: 3, is_active: true },

  // WIMPERN — Volumen Soft/Medium
  { id: 4, category_id: 1, subcategory_name: "Volumen Soft/Medium", treatment_name: "Volumen Soft / Medium", variant_name: "Neuset", duration: "105 Min.", price: 80, price_display: "80 €", display_order: 4, is_active: true },
  { id: 5, category_id: 1, subcategory_name: "Volumen Soft/Medium", treatment_name: "Volumen Soft / Medium", variant_name: "Auffüllen 3 Wochen", duration: "60 Min.", price: 40, price_display: "40 €", display_order: 5, is_active: true },
  { id: 6, category_id: 1, subcategory_name: "Volumen Soft/Medium", treatment_name: "Volumen Soft / Medium", variant_name: "Auffüllen 4 Wochen", duration: "75 Min.", price: 50, price_display: "50 €", display_order: 6, is_active: true },

  // WIMPERN — Mega Volumen
  { id: 7, category_id: 1, subcategory_name: "Mega Volumen", treatment_name: "Mega Volumen", variant_name: "Neuset", duration: "120 Min.", price: 95, price_display: "95 €", display_order: 7, is_active: true },
  { id: 8, category_id: 1, subcategory_name: "Mega Volumen", treatment_name: "Mega Volumen", variant_name: "Auffüllen 3 Wochen", duration: "60 Min.", price: 50, price_display: "50 €", display_order: 8, is_active: true },
  { id: 9, category_id: 1, subcategory_name: "Mega Volumen", treatment_name: "Mega Volumen", variant_name: "Auffüllen 4 Wochen", duration: "75 Min.", price: 65, price_display: "65 €", display_order: 9, is_active: true },

  // WIMPERN — Russian Volumen
  { id: 10, category_id: 1, subcategory_name: "Russian Volumen", treatment_name: "Russian Volumen", variant_name: "Neuset", duration: "120 Min.", price: 100, price_display: "100 €", display_order: 10, is_active: true },
  { id: 11, category_id: 1, subcategory_name: "Russian Volumen", treatment_name: "Russian Volumen", variant_name: "Auffüllen 3 Wochen", duration: "75 Min.", price: 80, price_display: "80 €", display_order: 11, is_active: true },
  { id: 12, category_id: 1, subcategory_name: "Russian Volumen", treatment_name: "Russian Volumen", variant_name: "Auffüllen 4 Wochen", duration: "90 Min.", price: 90, price_display: "90 €", display_order: 12, is_active: true },

  // WIMPERN — Lifting
  { id: 13, category_id: 1, subcategory_name: "Lifting", treatment_name: "Wimpernlifting", variant_name: "Standard", duration: "45 Min.", price: 50, price_display: "50 €", display_order: 13, is_active: true },
  { id: 14, category_id: 1, subcategory_name: "Lifting", treatment_name: "Wimpernlifting inkl. Färben", variant_name: "Inklusive Färben & Keratin", duration: "60 Min.", price: 70, price_display: "70 €", display_order: 14, is_active: true },

  // GESICHTSREINIGUNG & PFLEGE
  { id: 15, category_id: 2, subcategory_name: null, treatment_name: "Gesichtsreinigung inkl. Anti-Aging", variant_name: "Klassisch", duration: "60 Min.", price: 80, price_display: "80 €", display_order: 15, is_active: true },
  { id: 16, category_id: 2, subcategory_name: null, treatment_name: "Microneedling", variant_name: "Kollagen-Therapie", duration: "75 Min.", price: 90, price_display: "90 €", display_order: 16, is_active: true },
  { id: 17, category_id: 2, subcategory_name: null, treatment_name: "Hollywood Glow", variant_name: "Signature Facial", duration: "60 Min.", price: 95, price_display: "95 €", display_order: 17, is_active: true },
  { id: 18, category_id: 2, subcategory_name: null, treatment_name: "Hollywood Peel", variant_name: "Carbon Laser Peeling", duration: "90 Min.", price: 120, price_display: "120 €", display_order: 18, is_active: true },
  { id: 19, category_id: 2, subcategory_name: null, treatment_name: "Microdermabrasion", variant_name: "Hautverfeinerung", duration: "60 Min.", price: 80, price_display: "80 €", display_order: 19, is_active: true },
  { id: 20, category_id: 2, subcategory_name: null, treatment_name: "LED Lichttherapie", variant_name: "Phototherapie", duration: "40 Min.", price: 80, price_display: "80 €", display_order: 20, is_active: true },

  // PERMANENT MAKE-UP — Powder Brows
  { id: 21, category_id: 3, subcategory_name: "Powder Brows", treatment_name: "Powder Brows", variant_name: "Erstbehandlung", duration: "150 Min.", price: 350, price_display: "350 €", display_order: 21, is_active: true },
  { id: 22, category_id: 3, subcategory_name: "Powder Brows", treatment_name: "Powder Brows", variant_name: "Auffrischung nach 12 Monaten", duration: "90 Min.", price: 200, price_display: "200 €", display_order: 22, is_active: true },
  { id: 23, category_id: 3, subcategory_name: "Powder Brows", treatment_name: "Powder Brows", variant_name: "Auffrischung nach 24 Monaten", duration: "120 Min.", price: 150, price_display: "150 €", display_order: 23, is_active: true },

  // PERMANENT MAKE-UP — Ombre Brows
  { id: 24, category_id: 3, subcategory_name: "Ombre Brows", treatment_name: "Ombre Brows", variant_name: "Erstbehandlung", duration: "150 Min.", price: 350, price_display: "350 €", display_order: 24, is_active: true },
  { id: 25, category_id: 3, subcategory_name: "Ombre Brows", treatment_name: "Ombre Brows", variant_name: "Auffrischung nach 12 Monaten", duration: "90 Min.", price: 200, price_display: "200 €", display_order: 25, is_active: true },
  { id: 26, category_id: 3, subcategory_name: "Ombre Brows", treatment_name: "Ombre Brows", variant_name: "Auffrischung nach 24 Monaten", duration: "120 Min.", price: 150, price_display: "150 €", display_order: 26, is_active: true },

  // PERMANENT MAKE-UP — Lippen
  { id: 27, category_id: 3, subcategory_name: "Lippen", treatment_name: "Lippenpigmentierung", variant_name: "Soft Lips", duration: "120 Min.", price: 300, price_display: "300 €", display_order: 27, is_active: true },
  { id: 28, category_id: 3, subcategory_name: "Lippen", treatment_name: "Lippenpigmentierung", variant_name: "Aquarell", duration: "150 Min.", price: 350, price_display: "350 €", display_order: 28, is_active: true },
  { id: 29, category_id: 3, subcategory_name: "Lippen", treatment_name: "Lippenpigmentierung", variant_name: "Mit Lifteffekt", duration: "180 Min.", price: 360, price_display: "360 €", display_order: 29, is_active: true },

  // SCHULUNGEN
  { id: 30, category_id: 4, subcategory_name: null, treatment_name: "Lash Lift", variant_name: "Tageskurs inkl. Zertifikat", duration: "1 Tag", price: 400, price_display: "400 €", display_order: 30, is_active: true },
  { id: 31, category_id: 4, subcategory_name: null, treatment_name: "Wimpern", variant_name: "1:1 & Volumentechnik", duration: "2 Tage", price: 900, price_display: "900 €", display_order: 31, is_active: true },
  { id: 32, category_id: 4, subcategory_name: null, treatment_name: "PMU", variant_name: "Powder Brows Intensiv", duration: "3 Tage", price: 1500, price_display: "1.500 €", display_order: 32, is_active: true },
  { id: 33, category_id: 4, subcategory_name: null, treatment_name: "Microneedling", variant_name: "Apparative Kosmetik", duration: "1 Tag", price: 500, price_display: "500 €", display_order: 33, is_active: true },
  { id: 34, category_id: 4, subcategory_name: null, treatment_name: "Alle Schulungen insgesamt", variant_name: "Komplettausbildung Beauty Expert", duration: "Kombikurs", price: 3000, price_display: "3.000 €", display_order: 34, is_active: true },
];

export const DEFAULT_GALLERY: GalleryItem[] = [
  {
    id: 1,
    image_url: "/images/treatments/lash-lift-result.jpg",
    caption: "Wimpernlifting & Keratinlaminierung — Natürlicher Schwung & Glanz",
    category: "Wimpern",
    is_before_after: false,
    display_order: 1,
    is_active: true,
  },
  {
    id: 2,
    image_url: "/images/treatments/microneedling-facial.jpg",
    caption: "Apparatives Microneedling — Präzise Wirkstoffinfusion für strahlenden Teint",
    category: "Gesichtsreinigung & Pflege",
    is_before_after: false,
    display_order: 2,
    is_active: true,
  },
  {
    id: 3,
    image_url: "/images/treatments/lash-lift-macro.jpg",
    caption: "Lash Lift Makroaufnahme — Tiefschwarzer Mascara-Effekt ohne Verklumpen",
    category: "Wimpern",
    is_before_after: false,
    display_order: 3,
    is_active: true,
  },
  {
    id: 4,
    image_url: "/images/treatments/murvet-at-work.jpg",
    caption: "Mürvet in Aktion — Individuelle Hautbehandlung nach höchsten Standards",
    category: "Gesichtsreinigung & Pflege",
    is_before_after: false,
    display_order: 4,
    is_active: true,
  },
  {
    id: 5,
    image_url: "https://images.unsplash.com/photo-1597225244660-1cd128c64284?auto=format&fit=crop&w=1200&q=85",
    caption: "Powder Brows Heilungsergebnis nach 4 Wochen",
    category: "Permanent Make-up",
    is_before_after: false,
    display_order: 5,
    is_active: true,
  },
  {
    id: 6,
    image_url: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=85",
    caption: "Aquarell Lippenpigmentierung mit natürlicher Kontur",
    category: "Permanent Make-up",
    is_before_after: false,
    display_order: 6,
    is_active: true,
  },
];

export const DEFAULT_OPENING_HOURS: OpeningHour[] = [
  { id: 1, day_of_week: 1, day_name: "Montag", open_time: "09:00", close_time: "19:00", is_closed: false, custom_label: null, display_order: 1 },
  { id: 2, day_of_week: 2, day_name: "Dienstag", open_time: "09:00", close_time: "19:00", is_closed: false, custom_label: null, display_order: 2 },
  { id: 3, day_of_week: 3, day_name: "Mittwoch", open_time: "09:00", close_time: "19:00", is_closed: false, custom_label: null, display_order: 3 },
  { id: 4, day_of_week: 4, day_name: "Donnerstag", open_time: "09:00", close_time: "19:00", is_closed: false, custom_label: null, display_order: 4 },
  { id: 5, day_of_week: 5, day_name: "Freitag", open_time: "09:00", close_time: "19:00", is_closed: false, custom_label: null, display_order: 5 },
  { id: 6, day_of_week: 6, day_name: "Samstag", open_time: "10:00", close_time: "16:00", is_closed: false, custom_label: null, display_order: 6 },
  { id: 7, day_of_week: 7, day_name: "Sonntag", open_time: null, close_time: null, is_closed: true, custom_label: "Geschlossen (Nur nach Absprache)", display_order: 7 },
];

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  business_name: "Aura Glow by Mürvet",
  owner_name: "Mürvet Dincer",
  street: "Ernst-Moritz-Arndt-Straße 13",
  postal_code: "31224",
  city: "Peine",
  country: "Deutschland",
  phone: "+491739026031",
  phone_display: "+49 173 9026031",
  email: "kontakt@auraglow.de",
  whatsapp: "+491739026031",
  instagram_url: "https://instagram.com/aura6low",
  google_maps_url: "https://maps.google.com/?q=Ernst-Moritz-Arndt-Stra%C3%9Fe+13+31224+Peine",
  booking_info: "Termine nur nach vorheriger Vereinbarung.",
};

export const DEFAULT_BRAND_SETTINGS: BrandSettings = {
  brand_name: "Aura Glow by Mürvet",
  tagline: "Beauty & Aesthetics",
  primary_color: "#B88770",
  secondary_color: "#EFE6DD",
  accent_color: "#936650",
  background_color: "#F7F3EE",
  text_primary: "#392D29",
  text_secondary: "#756A63",
};

export const DEFAULT_DESIGN_SETTINGS: Record<string, DesignSectionSetting> = {
  hero: {
    section_id: "hero",
    background_color: "#211A18",
    background_image_desktop: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=2000&q=85",
    background_image_mobile: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85",
    image_position: "center center",
    image_size: "cover",
    overlay_color: "#211A18",
    overlay_opacity: 0.45,
    text_color: "#FFFFFF",
  },
  intro: {
    section_id: "intro",
    background_color: "#F7F3EE",
    text_color: "#392D29",
    overlay_opacity: 0,
  },
  treatments: {
    section_id: "treatments",
    background_color: "#FAF6F1",
    text_color: "#392D29",
    overlay_opacity: 0,
  },
  philosophy: {
    section_id: "philosophy",
    background_color: "#211A18",
    background_image_desktop: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=2000&q=80",
    image_position: "center center",
    image_size: "cover",
    overlay_color: "#211A18",
    overlay_opacity: 0.65,
    text_color: "#FFFFFF",
  },
  gallery: {
    section_id: "gallery",
    background_color: "#F7F3EE",
    text_color: "#392D29",
    overlay_opacity: 0,
  },
  pricing_cta: {
    section_id: "pricing_cta",
    background_color: "#EFE6DD",
    text_color: "#392D29",
    overlay_opacity: 0,
  },
  about_murvet: {
    section_id: "about_murvet",
    background_color: "#FAF6F1",
    text_color: "#392D29",
    overlay_opacity: 0,
  },
  appointment_cta: {
    section_id: "appointment_cta",
    background_color: "#211A18",
    background_image_desktop: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=2000&q=85",
    image_position: "center center",
    image_size: "cover",
    overlay_color: "#211A18",
    overlay_opacity: 0.70,
    text_color: "#FFFFFF",
  },
  footer: {
    section_id: "footer",
    background_color: "#211A18",
    text_color: "#FFFFFF",
    overlay_opacity: 0,
  },
};

export const DEFAULT_CONTENT_SECTIONS: Record<string, ContentSection> = {
  hero: {
    section_id: "hero",
    title: "Aura Glow by Mürvet",
    eyebrow: "Beauty & Aesthetics by Mürvet",
    headline: "Deine Schönheit.\nUnser Anspruch.",
    body_text: "Entdecke individuelle Beauty-Behandlungen für deine natürliche Schönheit und ein strahlendes Selbstbewusstsein.",
    primary_cta_label: "Termin anfragen",
    primary_cta_url: "/termin",
    secondary_cta_label: "Behandlungen entdecken",
    secondary_cta_url: "/leistungen",
  },
  intro: {
    section_id: "intro",
    title: "Philosophie & Handwerk",
    eyebrow: "AURA GLOW BY MÜRVET",
    headline: "Schönheit beginnt dort, wo du dich selbst wohlfühlst.",
    body_text: "In unserem Studio vereinen wir präzises Handwerk, meisterhafte Ästhetik und erstklassige Behandlungen zu einem ganzheitlichen Wohlfühlerlebnis. Jeder Blick, jede Kontur und jedes Hautbedürfnis ist einzigartig – genau so behandeln wir dich.",
    primary_cta_label: "Mehr über uns",
    primary_cta_url: "/ueber-uns",
  },
  philosophy: {
    section_id: "philosophy",
    title: "Unser Leitgedanke",
    eyebrow: "EXKLUSIVITÄT & PRÄZISION",
    headline: "Individuelle Ästhetik statt Einheitslook.",
    body_text: "Wir glauben an sanfte Betonung, harmonische Proportionen und höchste Produktqualität. Ob langanhaltendes Wimperndesign, makellose Puderbrauen oder regenerierende Facials: Deine Ausstrahlung steht im Mittelpunkt.",
    primary_cta_label: "Alle Behandlungen ansehen",
    primary_cta_url: "/leistungen",
  },
  about_murvet: {
    section_id: "about_murvet",
    title: "Die Gründerin",
    eyebrow: "ÜBER MÜRVET",
    headline: "Leidenschaft für feine Ästhetik und perfekte Linien.",
    body_text: "Mit geschultem Blick für Symmetrie und natürlicher Harmonie widmet sich Mürvet der individuellen Schönheit jeder Kundin. Jede Behandlung wird mit Geduld, meisterhafter Präzision und höchsten Hygienestandards ausgeführt.",
    primary_cta_label: "Persönlichen Termin anfragen",
    primary_cta_url: "/termin",
  },
  appointment_cta: {
    section_id: "appointment_cta",
    title: "Bereit für deinen Glow?",
    eyebrow: "ZEIT FÜR DICH",
    headline: "Gönne dir deine persönliche Auszeit.",
    body_text: "Vereinbare jetzt ganz unkompliziert deine individuelle Terminanfrage. Wir beraten dich typgerecht und finden die perfekte Behandlung für dich.",
    primary_cta_label: "Jetzt Termin anfragen",
    primary_cta_url: "/termin",
    secondary_cta_label: "Preise ansehen",
    secondary_cta_url: "/preise",
  },
};

export const DEFAULT_SEO_SETTINGS: Record<string, SeoSetting> = {
  home: {
    route: "/",
    title: "Aura Glow by Mürvet | Exklusive Beauty & Aesthetics",
    description: "Premium Beauty & Aesthetics Studio für Wimpernverlängerung, Permanent Make-up, Hollywood Glow Facials und zertifizierte Schulungen.",
  },
  services: {
    route: "/leistungen",
    title: "Behandlungen & Leistungen | Aura Glow by Mürvet",
    description: "Entdecke unser exklusives Leistungsangebot: Wimpern, Gesichtsreinigung & Anti-Aging, Permanent Make-up und professionelle Schulungen.",
  },
  pricing: {
    route: "/preise",
    title: "Preise & Konditionen | Aura Glow by Mürvet",
    description: "Transparente Preisübersicht für alle Beauty- und Aesthetics-Behandlungen von Aura Glow by Mürvet.",
  },
  gallery: {
    route: "/galerie",
    title: "Galerie & Impressionen | Aura Glow by Mürvet",
    description: "Authentische Einblicke in unsere Behandlungsresultate und die elegante Atmosphäre im Studio.",
  },
  about: {
    route: "/ueber-uns",
    title: "Über Mürvet & Studio-Philosophie | Aura Glow by Mürvet",
    description: "Lerne die Philosophie hinter Aura Glow kennen: Höchste Handwerkskunst, individuelle Beratung und moderne Ästhetik.",
  },
  contact: {
    route: "/kontakt",
    title: "Kontakt & Anfahrt | Aura Glow by Mürvet",
    description: "Nimm Kontakt mit Aura Glow by Mürvet auf. Wir freuen uns auf deine Nachricht oder deinen Besuch.",
  },
  appointment: {
    route: "/termin",
    title: "Terminanfrage | Aura Glow by Mürvet",
    description: "Frage jetzt unverbindlich deinen Wunschtermin für deine individuelle Beauty-Behandlung an.",
  },
  impressum: {
    route: "/impressum",
    title: "Impressum | Aura Glow by Mürvet",
    description: "Rechtliche Angaben und Impressum gemäß § 5 TMG für Aura Glow by Mürvet.",
  },
  datenschutz: {
    route: "/datenschutz",
    title: "Datenschutzerklärung | Aura Glow by Mürvet",
    description: "Informationen zur Verarbeitung deiner personenbezogenen Daten gemäß DSGVO.",
  },
};
